# Generated by Django 5.2.3 on 2025-06-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMongoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('basemongomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='chat.basemongomodel')),
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_group', models.BooleanField(default=False)),
                ('admin_id', models.IntegerField()),
                ('members', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
            bases=('chat.basemongomodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('basemongomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='chat.basemongomodel')),
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=50)),
                ('sender_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('media', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField()),
                ('status', models.JSONField(blank=True, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=50, null=True)),
                ('is_forwarded', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
            bases=('chat.basemongomodel',),
        ),
    ]
